### ISSUE TITLE
Creation of vector in the body of a `every` arises an error

### ISSUE THREAD

**Issue by rodrimc** [fsantanna/ceu#102]
The following code doesn't compile:
```
every 1s do
  vector[] byte vet = [] .. "";
end
```
Error: invalid `finalize´ : unexpected enclosing `every`

Version: 4bff92ce3b05ba99ce0e4ad4829e782ea6993156

**Comment by fsantanna** [comment]
This was fixed in e8333f29f8cb9cfb02df13cb52b3a2339db1e7b3.
(Only for upcoming v0.30)
