### ISSUE TITLE
Odd behavior when assigning the return of a Lua code to a vector

### ISSUE THREAD

**Issue by rodrimc** [fsantanna/ceu#110]
```
 var []byte b = [] .. "aaa";
  _printf ("%s\n", &&b[0]);

  b = [] .. [[ "b" ]];
  _printf ("%s\n", &&b[0]);
```
The output should be:
```
aaa
b
```
but instead it is:
```
aaa
baa
```

It works if one concatenates a ` '\0'`.

**Comment by fsantanna** [comment]
This is because strings in C are zero terminated but not in Lua. It is common to use Lua strings to hold binary data. You have to insert the \0 if you want to convert to a C string.

**Comment by rodrimc** [comment]
But the assignment 
```
b = [] .. [[ "b" ]];
```
shouldn't create a new vector and, therefore, discard the old content?

**Comment by fsantanna** [comment]
Yes, `$b` should be `1`, but you are passing a raw pointer to C, which will interpret it as a null terminating string in the context you are using it (`&s`).
