### ISSUE TITLE
invalid declaration : vector inside `code/tight`

### ISSUE THREAD

**Issue by rodrimc** [fsantanna/ceu#114]
Declaring a vector inside a `code/tight` raises the error: 
```
invalid declaration : vector inside `code/tight`
```

Is this a valid message or a bug?

Compiling the following source leads to this scenario.
```
code/tight Code (none) -> int
do
  var[] byte dummy = _;
  escape 0;
end

var int zero = call Code();
escape zero;
```

Version: 57f8c345ca097b9e77031427b814a6bbe60dbbd5

**Comment by rodrimc** [comment]
A `code/await` doesn't have this behavior.

**Comment by fsantanna** [comment]
It is a valid message.
Anything that depends on implicit control flow, such as `par/or` and automatic memory deallocation, can only be inside a `code/await`.
