### ISSUE TITLE
make samples gives errors

### ISSUE THREAD

**Issue by wluker** [fsantanna/ceu#122]
Following the instructions given in README.md I ran 

```
$ make samples
```

and all of the samples give an error

```
>>> ERROR : expected option `ceu-features-dynamic`
```

I'm running this on archlinux with lua-5.3.4-2.

Interesting language you've developed. I'm excited to start playing with it.

**Comment by fsantanna** [comment]
Thank you. This is a bug.
Forgot to add a command-line option after a change on the compiler...
