### ISSUE TITLE
pointer access across await

### ISSUE THREAD

**Issue by Johnicholas** [fsantanna/ceu#19]
I don't know if this is a bug, or a misconception

// There are some other processes that are generating and sending pointers-to-int
class Queue with
  event int* next;
do
  // nothing
end

// The customer wants to consume one of the pointers-to-int,
// but it also wants to do something (twiddle thumbs) in the meantime.
class Customer with
  var Queue& barbers;
do
  var int* c = null;
  par/or do
    _printf("twiddle thumbs while waiting\n");
    await FOREVER;
  with
    c = await barbers.next;
  end
  if c then
    _printf("got one\n");
  else
    _printf("didn't get one\n");
  end
end

This code gives me a "pointer access across await" error, and I don't know to rewrite it to do something equivalent that doesn't cause that error. Am I using Ceu wrongly, or is there a bug in the analysis?

**Comment by fsantanna** [comment]
The pointer assignment/use is crossing a "par/or" rejoin, what is currently not allowed.
We may accept this program in the future, given that the assignment/rejoin/use occurs in the same reaction.
How difficult is to rewrite your code to get rid of the error?
I guess you wrote a simpler version and compiling it is not as simple as moving the "if c then..." to inside the "par/or".

**Comment by Johnicholas** [comment]
The general pattern is: An organism is trying to acquire a pointer to something (by awaiting). The organism also wants to engage in an "idling" activity, which takes up as much time as necessary, but should be terminated when the organism can progress in its actual task.

Maybe this snippet conveys the (more complicated real task) more convincingly.

var Foo* ptr = null;
par/or do
  _idle();
  await FOREVER;
with
  ptr = await generator;
end
_assert(ptr);
watching ptr do
  _something();
end

I'll keep looking for a rewrite that doesn't involve crossing a par/or rejoin; it's probably a failure of imagination on my part.

**Comment by fsantanna** [comment]
Fair enough.

As a workaround, you can declare Foo as a "plain" pointer:
```
var Foo[] ptr = null;
```

(I also have a "TODO" with a similar pattern and workaround.)

**Comment by fsantanna** [comment]
Sorry, this is older than 1 year!

Using `escape`, you can assign safely to the pointer that syntactically crosses a `par`:

```
var u8&& ptr =
    par do
        //_idle();
        await FOREVER;
    with
        await 1s;
        escape null;
    end;
escape ptr == null;  // yields 1
```
