### ISSUE TITLE
Céupedia is broken

### ISSUE THREAD

**Issue by JobLeonard** [fsantanna/ceu#29]
![screenshot from 2015-06-30 11 29 50](https://cloud.githubusercontent.com/assets/259840/8426873/b48f00ae-1f1b-11e5-8523-cb5a79502cf9.png)

**Comment by fsantanna** [comment]
Thanks for the notification.
Looks like something related to PCRE being upgraded in the server.
I've already contacted the support.

**Comment by fsantanna** [comment]
It should be fixed now.
