### ISSUE TITLE
Using ceu on OSX

### ISSUE THREAD

**Issue by flippyhead** [fsantanna/ceu#30]
Is this possible and do you have any suggestions on setup?

Thanks!

**Comment by fsantanna** [comment]
I never tried before but it should be possible, as Céu only depends on `lua-5.1`, `lpeg-0.12` and `gcc`:
http://www.ceu-lang.org/wiki/index.php?title=C%C3%A9u_Manually

You still need an "environment" that provides you the events and system calls to use from Céu.
We have prepared SDL and Arduino to work with Céu.
I suppose you want to use SDL, which is well supported on MacOS, so you need to follow the specific steps for this environment:
http://www.ceu-lang.org/wiki/index.php?title=SDL

Let me know if this information is enough for your progress.

**Comment by fsantanna** [comment]
Some user-contributed instructions:
https://github.com/schorg/ceu-osx
