### ISSUE TITLE
Suspicious nondeterminism warning

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#32]
In this case I got **WRN : nondeterminism : variable/event rawWriteByte vs variable/event up** which shouldn't appear:

    class Receiver with
        var Parser& up;
        var Frame& rx;
        emit void evtReady;
    do
        par do
            every pB in up.evtByte do
                rx.rawWriteByte(pB);
            end
        with
            every up.evtStop do
                emit evtReady;
            end
        end
    end

**Comment by fsantanna** [comment]
ok
