### ISSUE TITLE
Segmentation fault when looping through a Céu vector

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#34]
I wrote the following code

```
var u8[5] foo = [1, 2, 3, 4];

loop i in $$foo do
	_printf("(%d): %d\n", i, foo[i]);
end

escape 42;
```
resulting in the following output during runtime
```
(0): 1
(1): 2
(2): 3
(3): 4
[application.ceu:7] runtime error: access out of bounds
Segmentation fault (core dumped)
```

The <b>access out of bounds</b> exception is correct because we loop for the maximum length (= 5) but vector only has length of 4, so accessing <i>foo[4]</i> is illegal. But the <b>segmentation fault</b> should not appear and the Céu application should still escape value 42.

**Comment by fsantanna** [comment]
There are no recoverable exceptions in Céu, i.e., the program should terminate with the message.
However, the `segfault` shouldn't happen in any case.

**Comment by mterber** [comment]
Ok, I just expected the program to escape 42 because of the following example:
```
var u8[2] foo;

foo = [] .. foo .. [4];
foo = [] .. foo .. [2];
foo = [] .. foo .. [7];

escape 42;
```

In this case obviously an <b>access out of bounds</b> error appears but the program nonetheless escapes 42:
```
[application.ceu:5] runtime error: access out of bounds
*** END: 42
```

So should it <b>always</b> terminate <b>immediately</b> after a runtime error message?

**Comment by fsantanna** [comment]
Yes, immediately.
Can you try to compile the final `.c` with `-DCEU_DEBUG` ?
I think this is the whole problem. The underlying `assert` is not being called, which explains the `segfault` and also why my tests aren't catching such a simple bug.

**Comment by mterber** [comment]
Sure. This leads to the following output:
```
(0): 1
(1): 2
(2): 3
(3): 4
[application.ceu:4] runtime error: access out of bounds
a.out: application.ceu:3558: ceu_sys_assert: Assertion `v' failed.
Aborted (core dumped)
```

**Comment by fsantanna** [comment]
Ok. Now the behavior is correct and the error also appears in the correct line.
I'll leave this issue open because of the `-DCEU_DEBUG` requirement.

**Comment by mterber** [comment]
Just as a complementary:

Now also the behaviour of the other example is correct...
```
var u8[2] foo;

foo = [] .. foo .. [4];
foo = [] .. foo .. [2];
foo = [] .. foo .. [7];

escape 42;
```
now leads to
```
[application.ceu:5] runtime error: access out of bounds
a.out: application.ceu:3557: ceu_sys_assert: Assertion `v' failed.
Aborted (core dumped)
```
means that it is terminated <b>immediately</b> after the error message without escaping 42 - as you specified!

**Comment by fsantanna** [comment]
Can you confirm if these applications crash with the correct message (even without `-DCEU_DEBUG`)?

**Comment by mterber** [comment]
Yes. Both examples crash with the correct assertion message even without -DCEU_DEBUG.
