### ISSUE TITLE
Suspicious tight loop warning

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#35]
Given the following code
```
var u8[5] foo = [1, 2, 3, 4];

loop i in $$foo do
	_printf("(%d): %d\n", i, foo[i]);
end

escape 42;
```

I retrieve a <b>tight loop</b> warning
```
ceu --safety 1 application.ceu
WRN [0000] : application.ceu : line 6 : WRN [0000] : application.ceu : line 6 : tight loop
gcc main.c
```

Is that correct? If I use <b>$$foo</b>, so the maximum length of the vector, this should be treated like using a <i>#define</i> instead because it can not be changed during runtime, can it? So when using <b>$foo</b> I would expect the warning but when using <b>$$foo</b> I wouldn't.

**Comment by fsantanna** [comment]
You are correct, this is a bug.

**Comment by fsantanna** [comment]
Should be fixed in the next commit.
