### ISSUE TITLE
Appending value to vector within a struct leads to runtime error

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#37]
<pre><code>data Frame with
  var u8[3] bytes;
end

var Frame[10] frames;
var Frame f1;

f1.bytes = f1.bytes .. [5]; // runtime error: access out of bounds

frames = frames .. [f1];
</code></pre>
When trying to append a new value to the vector "bytes" an "access out of bounds" error occurs during runtime. No compiler error is thrown.

**Comment by fsantanna** [comment]
This isn't supported yet.
At least, now you get an error message.
Changing to "enhancement".

**Comment by fsantanna** [comment]
1. Vectors in interfaces are not supported (i.e., `bytes` in `Frame`).
2. Array modifier in organism declaration (`var Frame[10] frames`) does not correspond to a normal vector. Instead, it creates that many instances of the class.

Regarding appending to vectors, this code compiles:

```
var u8[3] bytes;
bytes = [] .. bytes .. [5];
escape bytes[0];
```
