### ISSUE TITLE
Accessing tag within union leads to runtime error

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#38]
<pre><code>data Frame with
	tag DATA with
		var u8 d1;
		var u16 d2;
	end
	
	or
	
	tag RAW with
		var u8[3] bytes;
	end
end

var Frame f;
f.DATA.d1 = 4; // runtime error: invalid tag
</code></pre>
The code above generates a runtime error (invalid tag) when trying to access the DATA tag of frame f. No compiler error is thrown.

**Comment by fsantanna** [comment]
You have to use constructors to initialize tagged unions:
```
var Frame f = Frame.DATA(0,0);
f.DATA.d1 = 4; // now "f" is a "DATA"
```

or

```
var Frame f = Frame.DATA(4,0);
```

**Comment by mterber** [comment]
Ah ok!

Two further questions...

1. What does the constructor look like for initializing a vector within a union? So lets say I would like to initialize
<pre><code>var Frame f = Frame.RAW???
</code></pre>

I tried
<pre><code>var Frame f = Frame.RAW(0,0,0)
</code></pre>

but this didn't work.

2. Does the "constructor solution" mean that I can't switch between the two data representations (tags) during runtime like in C? I guess, on initialization, I have to decide whether I would like to create a DATA or a RAW frame but it is not possible to access the DATA tag byte-wise as a RAW tag, is it?

**Comment by fsantanna** [comment]
1. I was surprised that you could compile a vector inside a `data`. Of course the syntax exists and there's no reason why Céu should not support that, but it is not implemented yet (or even designed).

2. You can use the constructor as many times as you want to change the tag during runtime. But you cannot pretend that they are one or the other without explicitly saying so.

(The other issue you opened will remind me to look carefully about integrating `data` with vectors...)

**Comment by mterber** [comment]
1. Ok, thanks for the info!

2. Ok, but this means whenever I switch between the tags during runtime I have to use the constructor and I am forced to re-initialize the tag. This way the old value from the former tag gets lost, isn't it?

As an example, in "C" I can do the following:
<pre><code>union frame {
  uint16_t data;
  uint8_t raw[2];
};

int main(void) {
  union frame f;
  f.data = 4053;

  printf("data: %d\n", f.data);
  // prints 4053

  printf("raw (1. byte): %d, raw (2. byte): %d\n", f.raw[0], f.raw[1]);
  // prints raw (1. byte): 213, raw (2. byte): 15

  return 0;
}
</code></pre>

This way I can access the SAME binary data with two different interpretations (tags), first as one 16bit value, second as two 8bit values.

If I understood your constructor approach correctly that wouldn't be possible in Céu because whenever I switch the tag I have to call the constructor of the new tag and that way do a re-initialization -> no access to the binary data given by the former tag.

Is that true?

**Comment by fsantanna** [comment]
You are correct. That's considered unsafe and is the fundamental difference between "union" and "tagged union". If you want the "union" behavior, you'll have to define it in C and use it with the `_` prefix from Céu.

**Comment by mterber** [comment]
Ok understand, thanks!

One last question concerning this topic:
Is there any possibility to ask/check which tag is used for a specific tagged union during runtime?

Example
<pre></code>data Frame with
  tag DATA1 with
    var u8 a;
    var u8 b;
  end

  or

  tag DATA2 with
    var u8 a;
    var u8 b;
    var u8 c;
  end
end

class Test with
  var Frame& f;
do
  if("condition") then
    f = Frame.DATA1(...);
  else
    f = Frame.DATA2(...);
  end
end

var Frame f;
do Test with this.f = &f; end;

// how can I check here if "f" has been tagged as DATA1 or DATA2 within the "Test" organism?
// otherwise I don't know which tag to use to access the frames fields...
</code></pre>

**Comment by fsantanna** [comment]
Use the tag as a field:

```
if f.DATA1 then
    ...
end
```
