### ISSUE TITLE
Suspicious "missing alias operator" error

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#40]
Played around with the alias operator within data types and vectors and noticed the following
<pre><code>
data Test with
	var u8& b;
end

var u8 b = 7;
var Test[3] v;
var Test t;

t.b = &b;
v = v .. [t];

// reassignments
b = 10;  // OK
t.b = 88; // OK
v[0].b = 36; // invalid attribution : missing alias operator `&´
</code></pre>

The third reassignment leads to a "missing alias operator" error. Why?
"v[0]" should be evaluated to "t" and "t.b = ..." works perfectly fine...

**Comment by fsantanna** [comment]
Thanks.
This is a bug.

**Comment by fsantanna** [comment]
ok
