### ISSUE TITLE
Suspicious tight loop warning

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#41]
<pre><code>
event void c;

class Test with
	event void a;
	event void b;
do
	par/or do
		every a do
			_printf("a\n");
		end
	with	
		await b;
	end
end

watching c do
	loop do
		do Test;
	end
end
</code></pre>

Given the code above I get a <b>line 17 : tight loop</b> warning for the loop within the watching block although each trail within "Test" contains an "await" statement.

If I copy the execution body of "Test" directly into the loop within the watching block and declare the events a, b outside "Test", the warning disappears.

**Comment by fsantanna** [comment]
The problem is that the `kill` statement is immediate and can create a tight loop:

```
class Test with
do
    await FOREVER;
end

var Test t;
loop do
    par/or do
        await t;
    with
        kill t;
        await FOREVER;
    end
end
```

We could use some analysis, but we are taking the simple path now and just warn the user...

**Comment by mterber** [comment]
Ok. Means whenever I await for the termination of an organism this specific organism is treated by the temporal analysis as if he terminates immediately, so within the same reaction (because that would be always possible because of a "kill" statement somewhere else in the code) - regardless of the containing awaits!?

**Comment by fsantanna** [comment]
Exactly
