### ISSUE TITLE
Warning when accessing pointer provided by external event

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#43]
When trying to access a pointer provided via an external event
<pre><code>
input (char&&, u32) HTTP_GET;

loop do
  var char&& p2Buff;
  var u32 len;
  (p2Buff, len) = await HTTP_GET;
       
  var char c = p2Buff[0]; // doesn't work
end
</code></pre>

I get the following compiler warning

<pre><code>
application.ceu: In function ‘ceu_app_go’:
application.ceu:19:49: warning: passing argument 1 of ‘ceu_vector_geti_ex’ from incompatible pointer type
   var char c = p2Buff[0];
                                                 ^
In file included from main.c:30:0:
application.ceu:8438:7: note: expected ‘struct tceu_vector *’ but argument is of type ‘char **’
In file included from main.c:30:0:
application.ceu:15:10: warning: variable ‘__ceu_c_11’ set but not used [-Wunused-but-set-variable]
   var char&& p2Buff;
</code></pre>

**Comment by fsantanna** [comment]
should be fixed in the next commit

**Comment by fsantanna** [comment]
Still an error though.
It forces you to use an external type because indexing pointer is unsafe.
