### ISSUE TITLE
Strange behaviour on emitting internal event

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#44]
Hi,

I currently made a pull on your current master (0f6a7e1e9a9b216cce1db68fe9b92f3d13e35e4c) branch to get the latest bug fixes. After that I noticed that parts of my existing Céu code do not work anymore. I investigated the problem and noticed that it has to be associated with the internal event handling. Have a look at the following (senseless) code:

<pre><code>
input void KILL;

class OrgC with
do
	loop do
		await 1s;
		_printf("work\n");
	end
end

class OrgA with
	event void signal;
do
	var int test = 0;

	loop do
		watching signal do
			do OrgC;
		end
		test = test + 1;
		_printf("exit (%d)\n", test);
	end
end

class OrgB with
do
	var OrgA a;

	every 5s do
		emit a.signal;
		_printf("after EMIT\n");
	end
end

var OrgB b;
await KILL;
escape 42;
</code></pre>

This generates the following output:
<pre><code>
work
work
work
work
work
exit (1)
exit (2)
after EMIT
work
work
work
work
work
exit (3)
exit (4)
after EMIT
work
work
work
work
work
exit (5)
exit (6)
after EMIT
work
work
work
work
work
exit (7)
exit (8)
after EMIT
... and so on ...
</pre></code>

As far as I understood "exit (...)" should only appear once per emit. In this case it is printed twice which means the loop within 'OrgA' is executed twice within one reaction chain.

If I compile and execute the same Céu code with an older compiler version (df104dadf25bbb1e98413bb92c32d06987667e16) I get

<pre><code>
work
work
work
work
work
exit (1)
after EMIT
work
work
work
work
work
exit (2)
after EMIT
work
work
work
work
work
exit (3)
after EMIT
work
work
work
work
work
exit (4)
after EMIT
... and so on...
</code></pre>

which I think is the expected behaviour!

Maybe you could have some investigations on this problem?

Thanks!

**Comment by mterber** [comment]
Hint: The strange behaviour must have been introduced between accecdcfbb9f20bafdeec56d5cee22fea9c4941f (works as expected) and 89fa32d93b5dbf8f156ce1dbaee51491fd5bb4ab (shows the strange behaviour).

**Comment by mterber** [comment]
Correction:

Version df104dadf25bbb1e98413bb92c32d06987667e16 is the last one I know that worked for me as expected.

**Comment by fsantanna** [comment]
Thanks. This is a bug.
I am working on it.

**Comment by fsantanna** [comment]
Fixed in `master`.
Thanks for the detailed feedback.

**Comment by mterber** [comment]
Thanks for the quick fix!
