### ISSUE TITLE
Emit statement never returns

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#45]
Hi,

the problem reported in #44 is fixed and doesn't appear anymore. But still my code doesn't behave the same way as it did before. So I guess issue #44 might not have been the root cause. I investigated the problem again and noticed that it appears in the following szenario:

<pre><code>
input void KILL;

class OrgA with
	event void evtA;
	event void evtB;
do
	loop do
		watching evtA do
			loop do
				loop i in 3 do
					await 1s;
					_printf("work!\n");
				end
				emit evtB;
			end
		end
		_printf("exit WATCHING\n");
	end
end

class OrgB with
do
	var OrgA a;
	
	loop do
		await a.evtB;
		_printf("before EMIT\n");
		emit a.evtA;
		_printf("after EMIT\n");
	end
end

var OrgB b;

await KILL;

escape 42;
</code></pre>

This one provides the following output:
<pre><code>
work!
work!
work!
before EMIT
exit WATCHING
work!
work!
work!
work!
work!
work!
... and so on ...
</code></pre>

Means the <i>emit a.evtA</i> statement of 'OrgB' is never left! And this is exactly the problem I noticed in my code since I use newer versions of the Céu compiler.

I guess the problem might appear because evtB is emitted within the watching block in 'OrgA' and in the same reaction chain that processes evtB the wachting block is terminated by 'OrgB' by emitting evtA. So this might be some kind of <b>"we are sawing off the branch we are sitting on"</b> problem!?

In the older version 89af57dc8d7eb9173daa7d96288f3c9efc9d624d of the Céu compiler the same code generates the following output:

<pre><code>
work!
work!
work!
before EMIT
exit WATCHING
after EMIT
work!
work!
work!
before EMIT
exit WATCHING
after EMIT
work!
work!
work!
before EMIT
exit WATCHING
after EMIT
work!
work!
work!
... and so on ...
</code></pre>

The latest would be the expected behaviour (from my understanding).

**Comment by fsantanna** [comment]
I'm trying a new semantics and this behavior would be correct.
When an `emit` is aborted with things still reacting to it, everything is aborted.
Among other things, this allows the `emit` to pass pointers again (not already supported on `master`).

*"we are sawing off the branch we are sitting on"*

This is exactly what is happening in your code.

Here's the issue in its simplest form:

```
input void I;
event void e, f;
par do
    watching e do       // 5
        await I;        // 1
        emit f;         // 3, aborted on 5
        _assert(0);     // never executes
    end
    await I;
    escape 42;
with
    await f;            // 2
    emit e;             // 4, aborted on 5
    _assert(0);         // never executes
with
    async do
        emit I;
        emit I;
    end
end
```

The `emit-f` awakes the `await-f`, the `emit-e` awakes the `watching-e` which aborts the `emit-f` along with all pending computation that it started.

Can you work around this new behavior?

**Comment by mterber** [comment]
Ah, thank you very much for this minimal example! Now it is perfectly clear why my code doesn't work anymore. I will have to think about how to cope with that semantics change...

One thing I didn't understand:
Why is <i>emit-e</i> also aborted (according to your comments)? From my understanding it should only lead to the termination of the wachting-e block, then return and execute <i>_assert(0)</i>.

**Comment by fsantanna** [comment]
Because what generated the `emit-e` has been aborted.
Here's the stack trace:

```
I -> await-I -> emit-f -> await-f -> emit-e -> watching-e -> aborts-emit-f
       \---------------everything-in-between-aborts---------------/
```

Now we use `setjmp`/`longjmp` in the implementation.
When an abortion occurs, we do a `longjmp` to the lowest aborted level in the stack.

**Comment by mterber** [comment]
Sure, thanks! When looking at the stack trace it is obvious!

**Comment by fsantanna** [comment]
Reconsidering what I said...

This is wrong:

```
I -> await-I -> emit-f -> await-f -> emit-e -> watching-e -> aborts-emit-f
       \---------------everything-in-between-aborts---------------/
```

This is correct:

```
I -> await-I -> emit-f -> await-f -> EMIT-E -> watching-e -> aborts-emit-f
       \--------everything-not-in-the-lexical-scope-aborts--------/
// EMIT-E does not abort
```

**Comment by fsantanna** [comment]
Done.
Please, update to `master`.
You'll probably get some compile errors due to uninitialized variables.
Let me know if they make sense.

**Comment by mterber** [comment]
According to your new approach your example would look like this:

<pre><code>
input void I;
event void e, f;
par do
    watching e do // 5
        await I; // 1
        emit f; // 3, aborted on 5
// -----------------------------------------
// code, that never executes
// -----------------------------------------
    end
    await I;
    escape 42;
with
    await f; // 2
    emit e; // 4, aborted on 5
    _assert(0);
with
    async do
        emit I;
        emit I;
    end
end
</code></pre>

So what exactly is the difference between this approach and the behaviour before you introduced the "new semantics"? Isn't it the same?

**Comment by fsantanna** [comment]
The `_assert(0)` will execute and crash the application.
The `emit f` continuation aborts because it is inside the `watching` which aborted.
However, the continuation of `emit e` does not abort: even though it was started from something that aborted (the `emit f`), the `emit e` is not in the aborted scope and is not affected by the abortiong of `emit f`.

**Comment by fsantanna** [comment]
(Your original code should work again.)

**Comment by mterber** [comment]
Ok, thanks!

As you mentioned above I now get compile errors because of uninitialized variables, e.g.

<pre><code>
data Test with
	var u8 n;
end

var Test t;
t.n = 3;

_printf("%d\n", t.n);

escape 42;
</pre></code>

I get the error when accessing 't.n' on calling printf(). How to solve this?

**Comment by fsantanna** [comment]
The initialization must be in the constructor:
```
var Test t with
    this.n = 3;
end;
```

**Comment by mterber** [comment]
This

<pre><code>
data Test with
	var u8 n;
end

var Test t with
	this.n = 3;
end;

_printf("%d\n", t.n);

escape 42;
</code></pre>

leads to
<pre><code>
ceu --safety 1 application.ceu
ERR [0000] : application.ceu : line 6 : variable/event "n" is not declared
make: *** [all] Error 1
</code></pre>

**Comment by fsantanna** [comment]
Sorry, I misread as a `class`, but you are using a `data`:
```
data Test with
    var u8 n;
end

var Test t = Test(3);

_printf("%d\n", t.n);

escape 42;
```

(btw, the other code should give an error)

**Comment by mterber** [comment]
Ok... I should have remembered the constructor syntax for data types, sorry!

But this means that using C arrays within data types doesn't work anymore because they are now forced to be initialized within the constructor but this feature hasn't been implemented yet, has it?

For example in my current code I use data types like
<pre><code>
data Test with
  var u8 n;
  var _u8[10] v;
end
</code></pre>
But I guess, so far, there is no syntax implemented to initialize such a data type!?

**Comment by fsantanna** [comment]
No, sorry.
I think you have no workarounds because there's nothing you can put as an r-val when assigning to a vector that compiles in C:

```
u8 v[10];
v = ?;
```

I think we'll need a special syntax to prevent initializations errors for C types just because of vectors.

For now, I recommend that you edit `ref.lua` and change the offending line from `ASR` to `WRN`.
That changes all initialization errors to warnings.
