### ISSUE TITLE
Porting to NodeLua

### ISSUE THREAD

**Issue by Bazmundi** [fsantanna/ceu#46]
What is the likelihood of porting this to something like the ESP8266 which is already running Lua?

**Comment by fsantanna** [comment]
You don't need Lua to run Céu in the embedded device.
You will only need it in the cross-compile phase, which would generate the executable for the embedded device from your desktop running Linux/Max/Win.
The Céu compiler is written in Lua, not the runtime.

What you really need is access to a C-based SDK for `ESP8266`:
https://github.com/pfalcon/esp-open-sdk
Not sure if this is the best link, though.

(Sorry for the delay in the answers, I was on vacation w/o internet access.)

**Comment by Bazmundi** [comment]
No don't apologise.   I appreciate your responding.  I have been playing with esp8266 in background and realised it was likely luagravity I needed since that should be less fiddly than cross compiling ceu. So it actually started playing with luagravity on my PC last night as a break in my study.  I will try moving it onto nodelua etc at Christmas time when I have a break.

Cheers,
A

**Comment by fsantanna** [comment]
You might start faster with LuaGravity, but I recommend experimenting with Céu instead.
Céu is much more expressive considering the synchronous/reactive model. It provides the `par/or` construct, abstractions with organisms, first-class timers, etc.
