### ISSUE TITLE
No syntax for initializing data types containing C arrays

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#47]
So far, there is no syntax for initializing data types containing C arrays. But omitting the initialization leads to compiler errors such as <i>invalid access to uninitialized variable</i>.
    
<pre><code>
data Test with
  var _u8[10] v;
end

var Test t = Test(???);
</code></pre>

In #45 you suggested: "I think we'll need a special syntax to prevent initializations errors for C types just because of vectors."

The same problem might also belong to classes.

**Comment by fsantanna** [comment]
Now, external vectors at least require empty initialization (as a reminder):

```
var _u8[10] v = [];

data Test with
  var _u8[10] v;
end
var Test t = Test([]);
```

Fixed in branch `arch` and in the upcoming `v0.11`.
