### ISSUE TITLE
Pointers allowed as event type but can't be used

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#48]
In the following example the declaration of a pointer as event type for an internal event is allowed by the compiler.
<pre><code>
event u8&& a;  // allowed by compiler

var u8 k = 5;

emit a => &&k; // leads to compiler error
</code></pre>
But when <i>a</i> is actually emitted the compiler throws an error <b>wrong argument : cannot pass pointers</b>. Why does the compiler allow the declaration of an internal event carrying a pointer but refuses the actual usage? Isn't it kind of inconsistent?

**Comment by fsantanna** [comment]
Yes. It is a bug. Thanks.

**Comment by fsantanna** [comment]
ok
