### ISSUE TITLE
Alias - missing compiler error leads to segfault

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#49]
I accidentally wrote the following code:
  
<pre><code>
class Test with
	var u8[10]& v;
do
	v = [] .. v .. [4];
end

var u8[10]& v; // error: '&' must be deleted

do Test with
	this.v = &v;
end;
</code></pre>

The compiler didn't through any error but on runtime I got a SEGFAULT. Maybe there should be a compiler error to avoid that?

**Comment by fsantanna** [comment]
fixed. Now complains about "uninitialized variable"
