### ISSUE TITLE
Using pool alias leads to gcc compile error

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#50]
I used the following code to access the next organism within a pool:

<pre><code>
class Job with
    var u8 id = 0;
    event void nextRequest;
do
    // do job
    await 1s;
end

pool Job[10] jobs;
pool Job[10]& jobs_alias = &jobs;

var Job&& ptr = null;
loop j in jobs do
    ptr = j;
    break;
end // ok, no compile error

ptr = null;
loop j in jobs_alias do
    ptr = j;
    break;
end // compile error occurs
</code></pre>

When using the <b>jobs_alias</b> the following gcc compile errors occurs:

<pre><code>
ceu --safety 1 application.ceu
WRN [0000] : pools_organisms.ceu : line 13 : WRN [0000] : pools_organisms.ceu : line 13 : `loop´ iteration is not reachable
WRN [0000] : pools_organisms.ceu : line 19 : WRN [0000] : pools_organisms.ceu : line 19 : `loop´ iteration is not reachable
gcc -pthread main.c env/eq.c env/sig.c env/wclock.c -Wall -lrt -DCEU_DEBUG -g
In file included from main.c:29:0:
pools_organisms.ceu: In function ‘ceu_app_go’:
pools_organisms.ceu:19:42: error: ‘tceu_vector’ undeclared (first use in this function)
 loop j in jobs_alias do
                                          ^
pools_organisms.ceu:19:42: note: each undeclared identifier is reported only once for each function it appears in
pools_organisms.ceu:19:54: error: expected expression before ‘)’ token
 loop j in jobs_alias do
                                                      ^
pools_organisms.ceu:22:111: error: expected expression before ‘)’ token
 end
                                                                                                               ^
In file included from main.c:29:0:
main.c: At top level:
application.ceu:6799:13: warning: ‘_ceu_pre_1’ defined but not used [-Wunused-function]
make: *** [all] Error 1
</code></pre>

**Comment by fsantanna** [comment]
ok, fixed
