### ISSUE TITLE
Assigning "null" to class option pointer leads to segfault 

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#51]
When I assign <b>null</b> to the option pointer of a class I get an SEGFAULT error on runtime:

<pre><code>class Test with
do
end

var Test&&? a = null; // leads to segfault
</code></pre>

If I use a <b>data type</b> or <b>u8, int</b>, etc. the error doesn't occur.

**Comment by fsantanna** [comment]
ok, fixed
