### ISSUE TITLE
Confusing compiler warning

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#52]
Consider the following example:

<pre><code>
class Test with
	var u8 k;
do
end

do TestX with
  this.k = 5;
end;
</code></pre>

For sure, this leads to an compiler error because <b>TestX</b> is misspelled. In this case I would expect the compiler to give me a hint that class <b>TestX</b> ist not defined. Instead, the Céu compiler issues:

> variable/event "k" is not declared

The error message isn't wrong but it's kind of confusing since it doesn't inform about the root cause. I quite often struggled in such scenario looking for a misspelled interface variable being not aware of the typo in the class identifier.

**Comment by fsantanna** [comment]
Thanks for the report.

**Comment by fsantanna** [comment]
ok
