### ISSUE TITLE
Wired gcc compiler warning regarding unused loop variable

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#56]
Edited: 

The following code given
<pre><code>
var int k = 5;
loop/10 i in k do
	var int x = i + 2;
	_printf("%d\n", x);
end
</code></pre>
in the current master branch (150fea5fd098cf41216062cb87370404013f2db7) I receive the following compiler warning from gcc:

> application.ceu:3:9: warning: unused variable ‘__57’ [-Wunused-variable]
 loop/10 i in k do
         ^
So it states that 'i' is unused but this is obviously not the case.

**Comment by fsantanna** [comment]
Thanks, fixed in the `arch` branch.
The warning was about an internal variable to check if `/10` is really a constant:
```
int __57[10] = {};
```
