### ISSUE TITLE
Variable pool size leads to lua stack trace

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#58]
<pre><code>
class Org with
do
end

var int n = 5;
pool Org[n] a;
</code></pre>

This one leads to the following lua stack trace:

> lua: /usr/local/bin/ceu:12656: attempt to concatenate field 'sval' (a nil value)
stack traceback:
	/usr/local/bin/ceu:12656: in function 'tp2dcl'
	/usr/local/bin/ceu:13130: in function 'pre'
	/usr/local/bin/ceu:4478: in function 'visit_aux'
	/usr/local/bin/ceu:4491: in function 'visit_aux'
	/usr/local/bin/ceu:4491: in function 'visit_aux'
	/usr/local/bin/ceu:4491: in function 'visit_aux'
	/usr/local/bin/ceu:4491: in function 'visit_aux'
	/usr/local/bin/ceu:4491: in function 'visit_aux'
	/usr/local/bin/ceu:4491: in function 'visit_aux'
	/usr/local/bin/ceu:4491: in function 'visit_aux'
	/usr/local/bin/ceu:4491: in function 'visit_aux'
	/usr/local/bin/ceu:4491: in function 'visit_aux'
	/usr/local/bin/ceu:4491: in function </usr/local/bin/ceu:4462>
	(tail call): ?
	/usr/local/bin/ceu:13174: in main chunk
	[C]: ?

For sure, it is not allowed to specify a variable pool size (to get bounded memory) but I would expect an appropriate compiler error instead of a stack trace.

**Comment by fsantanna** [comment]
thanks.

**Comment by fsantanna** [comment]
Fixed in branch `arch`.
