### ISSUE TITLE
Unexpressive compiler error on pool assignment

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#59]
<pre><code>
class Org with
do
end

pool Org[5] a;
pool Org[5] b = a;
</code></pre>

Hi,

in this example I receive the following compiler error:
> ERR [0000] : application.ceu : line 8 : types mismatch (`Org[]´ <= `Org[]´)

I am aware that the assignment is not allowed but the error message is somewhat misleading as it states "_types mismatch_" but shows two equal types "`Org[]´ <= `Org[]´".

**Comment by fsantanna** [comment]
thanks.

**Comment by fsantanna** [comment]
Now it generates the message `line XX : invalid assignment : unexpected context for pool "a"`
