### ISSUE TITLE
Wired compiler error after par do block

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#61]
Hi,

in the current master branch (https://github.com/fsantanna/ceu/commit/d92ce09ea1b10ed0d8875cfd4d8c57221ea89074) the following code
<pre><code>input void HELLO;
input void WORLD;
par do      // par/and, par/or would behave the same
    loop do
        await HELLO;
        _printf("Hello!\n");
    end
with
    loop do
        await WORLD;
        _printf("World!\n");
    end
end

escape 0;</code></pre>

leads to the following compiler error:
> ERR : app.ceu : line 13 : before `end´ : expected statement (usually a missing `var´ or C prefix `_´)

Since the par do-end never rejoins, the escape statement is never reached. Consequently, I would expect some kind of "unreachable statement" warning. Instead, the provided message indicates an error inside the par do block which is obviously not the case. Might be confusing...

If I remember correctly, in C unreachable code, like in the example below, is just indicated by the C compiler as a warning but does not interrupt the compilation process. Maybe that would be a reasonable approach for Céu too? Or is it some special safety feature of Céu?
<pre><code>
int main(void) {
 <...>
 while(1);
 <...>
 return 0;
}
</code></pre>

**Comment by fsantanna** [comment]
It now generates `line 13 : after end : expected ; or end of file`.
This is syntax error in Céu: `par` can only appear as the last statement in a sequence.
