### ISSUE TITLE
Wired non terminating trail warning

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#63]
Hi,

the following code
```
input void LCLICK;
input void RCLICK;
input u8 KEY_DOWN;

par/or do
	await KEY_DOWN;
	escape 1;
with
	await LCLICK;
	await RCLICK;
	escape 0;
end
```
leads to the following warning:
> WRN [0000] : test.ceu : line 5 : WRN [0000] : test.ceu : line 5 : at least one trail should terminate

I don't know whether or not this is an issue. The last instruction in each trail of the par block is **escape**. Consequently, this terminates the whole program - in particular also the corresponding trail. So why does the compiler warn about non terminating trails?

I guess that the problem may be caused by the fact that an **escape** statement generally does not guarantee to terminate the whole program!? But it should always terminate the block which holds the corresponding **par do** thereby terminating the associated trails!? Shouldn't it?

**Comment by fsantanna** [comment]
The problem is regarding the `par/or`. In this case, it never terminates normally, i.e., from one of its trails reaching the last statement. Note that with a `par/and`, the behavior would be the same.
To avoid the warning you have to use a `par`.
