### ISSUE TITLE
Ceu compiler option "out-dir" behaves unexpected

### ISSUE THREAD

**Issue by mterber** [fsantanna/ceu#65]
Hi,

I am not sure whether this is an issue or just a misunderstanding. I would like to tell the Céu compiler to place the generated _ceu_app.c and _ceu_app.h in specific folder. For example I have a main.ceu in the current working directory and would like to place the generated files into folder "gen":

```
main.ceu
gen
  _ceu_app.c
  _ceu_app.h
```

This works pretty well using `ceu --out-dir gen main.ceu`. However, if there is a second ceu file involved which is included by main.ceu compilation fails:

```
test.ceu
main.ceu // includes test.ceu
gen
  _ceu_app.c
  _ceu_app.h
```
In this case the compiler states that there is no such file "test.ceu" available. To get it working I have to move test.ceu into the specified output directory:

```
main.ceu // includes test.ceu
gen
  test.ceu
  _ceu_app.c
  _ceu_app.h
```
It seems as if option "out-dir" also changes the current working directory of the compiler which is - at least from my point of view - an unexpected behaviour.

(I refer to https://github.com/fsantanna/ceu/commit/ba87141d312ced8e0c5cb0ff8fcff26d08136828)

**Comment by fsantanna** [comment]
In the new version, each output file must be specified with its full path.
