### ISSUE TITLE
Program doesn't terminate when `await async/thread` is next to `await`

### ISSUE THREAD

**Issue by calmattoso** [fsantanna/ceu#76]
Given the following test:
```c
par/or do
    await ThreadFail();
with
    _printf("Test starts!\n");
    await 3s;
    _printf("Test is over\n");
end

_printf("Done!\n");

escape 0;
```
We expect the program to terminate after `3s`.

However, given the following implementation of `ThreadFail`, termination becomes non-deterministic, due to the `await 1ms` statement:
```c
code/await ThreadFail (void) -> FOREVER do
    do finalize with
        _printf("ThreadFail is over!\n");
    end

    loop do
        await 1ms;

        await async/thread do
            _printf("Thread will sleep now...\n");
            _sleep(2);
            _printf("Thread woke up.\n");
        end
    end
end
```
Note that across multiple runs this was observed to sometimes terminate, but when or if are not guaranteed nor consistent. 

The program runs as expected if any of the following is done:
- Removing the `await 1ms` statement
- Wait longer, e.g. `500ms`.

**Comment by calmattoso** [comment]
Upon further testing it was found that this is only observed when using `ceu-libuv` as the underlying environment. When using `ceu-sdl` this problem is not encountered.

**Comment by fsantanna** [comment]
This is bug is actually from <https://github.com/fsantanna/ceu-libuv>.
Fixed there.
