### ISSUE TITLE
Different compilation results for same code

### ISSUE THREAD

**Issue by calmattoso** [fsantanna/ceu#77]
The compilation of the following code sometimes work, other times it fails:
```c
code/await Test(void) -> FOREVER do
    _printf("oi!\n");
    do finalize with
        await async/thread do
            _printf("tchau!\n");
        end
    end
    await FOREVER;
end

par/or do
    await Test();
with
    await 1ms;
end

escape 0;
```

Sometimes the error is shown:
```
ERR [0000] : src/test.ceu : line 8 : invalid `async/thread´ : unexpected enclosing `finalize´
```
Other times the program runs and prints the two messages.

This was observed on the `ceu-sdl` environment by running the compilation statement below directly in the command line.
```
ceu --pre --pre-args="-I$(CEU_DIR)/include -I$(CEU_SDL_DIR)/include" /
          --pre-input=$(INPUT) /
    --ceu --ceu-features-lua=true --ceu-features-thread=true /
          --ceu-err-unused=pass --ceu-err-uninitialized=pass /
    --env --env-types=$(CEU_DIR)/env/types.h /
          --env-threads=$(CEU_DIR)/env/threads.h /
          --env-main=$(CEU_DIR)/env/main.c /
    --cc  --cc-args="-llua5.3 -lpthread -lm -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lSDL2_gfx" /       
          --cc-output=test
```

**Comment by fsantanna** [comment]
Fixed recently. 
It should be an error all the time.
(Do you need this behavior or it is just a test?)

**Comment by calmattoso** [comment]
For the rabbitmq API potentially blocking calls are done in `finalize` blocks to close a connection, stop consuming, etc. I tried putting a thread around such calls and came across the reported behavior.

**Comment by fsantanna** [comment]
`finalize` must execute with zero delay, no synchronous statements allowed.
You'll probably need a custom data structure/linked list and an extra thread to free your resources.

**Comment by fsantanna** [comment]
A better solution is to have a pool of `code/await` that creates a thread to release the resource:
```
code/await Release (var <what-to-release> x) -> void do
    await async/thread (x) do
        _release(x);  // blocking call
    end
end

pool[] Release rs;

...
    do
        ...
    finalize (...) with
        spawn Release(...) in rs;
    end

**Comment by calmattoso** [comment]
Thanks! I'll use that strategy then.
