### ISSUE TITLE
Division seems to block the execution

### ISSUE THREAD

**Issue by rodrimc** [fsantanna/ceu#87]
The following code blocks in the division `3000.0/diff`:
```
 par/or do                                                                          
   await 5s;                                                                        
 with                                                                               
   var int count = 0;                                                               
   var int diff = 290 - 48;                                                         
   every (3000.0/diff)ms do                                           
     _printf ("%d\n", count);                                                       
     count = count + 1;                                                             
   end                                                                              
 end  
```
If we replace the literal `3000.0` to `3000` the program works. Apparently this behavior is observed by any value of `diff` that doesn't divide 3000 (i.e., if the remainder of the division `3000.0/diff` isn't `0`).

**Comment by rodrimc** [comment]
I forgot to inform the version I've tested: 5ea9e00b9d6369fdb6fc42ca6c4874a22963c167

**Comment by fsantanna** [comment]
This example also fails:
```
await (1.1)ms;
```
The problem is with floats and the interaction with the environment (you are running with `libuv`, right?).

The next commit will refuse non-integer values in awaits.

**Comment by rodrimc** [comment]
Not sure whether this is the best fix. I mean, for me it makes totally sense to write `await 1.1 ms` (being this semantically equivalent to `await 1100 us`).  

While I understand we can always convert units to avoid float values, I don't see the point to add this restriction to the language given the compiler can also internally perform these conversions.

**Comment by fsantanna** [comment]
Implicit type coersion is usually a bad idea.
In this case, it is even more dangerous because time is discrete in Céu and floating point arithmetic is tricky (e.g, a case you end up with something like `100h0min0s0ms1us`). Also, what about `1.5us`?
This convenience doesn't pay off and is inconsistent with the general mindset of the language.
Note that this fix restores the behavior of previous versions of Céu (and *also* solves the problem you described).
