### ISSUE TITLE
False positive compile error

### ISSUE THREAD

**Issue by rodrimc** [fsantanna/ceu#91]
The following code doesn't compile:

```
var int x;                                 
                                               
 code/tight   /* "line 85" */       
 Dummy (void) -> void do      
   /* nothing */                         
 end                                        
                                               
 escape 0;  
```
Error message:
`uninitialized variable "x" : reached yielding statement (./src/pong.ceu:85)` (this line is the declation code/tight)

version: 4bff92ce3b05ba99ce0e4ad4829e782ea6993156

**Comment by rodrimc** [comment]
Why the compiler seems to consider a `par` composition as 'yelding statement' ? Is this the expected behavior (if so, please explain me why) or is this a bug? The following code also doesn't compile:

```
var int x;
 par/or do 
   x = 0;     
 with          
   await FOREVER; 
 end  
```
Error: `uninitialized variable "x" : reached yielding statement`

Version: 4bff92ce3b05ba99ce0e4ad4829e782ea6993156

**Comment by fsantanna** [comment]
We refuse this kind of code because it is possible to access the variable from inside the `code/tight`:

```
var int x;                                 
code/tight Dummy (void) -> void do
    _printf("%d\n", outer.x);
end                                        
call Dummy();                                               
escape 1;  
```

What is the use case for declaring a `code` in between a declaration and initialization?

**Comment by fsantanna** [comment]
The second branch doesn't initialize `x`:
```
var int x;
 par/or do 
   x = 0;     
 with          
   await FOREVER; 
 end
```

We currently don't check if the branch that doesn't initialize the variable never terminates.
Alternatively, you could do something like this:
```
var int x = do
    par/or do
        ...
        escape 0;
    with
        ...
        await FOREVER;
    end
end;
```
